A first stab at firedrake support.
The example doesn't work. Crashes with a massive traceback, the last
few lines being

  File "/home/pfarrell/local/firedrake/firedrake/local/lib/python2.7/site-packages/tsfc/fem.py", line 316, in iterate_shape
    result.append(callback((ufl_element, c, flat_deriv)))
  File "/home/pfarrell/local/firedrake/firedrake/local/lib/python2.7/site-packages/tsfc/fem.py", line 364, in callback
    table = params.tabulation_manager[key]
  File "/home/pfarrell/local/firedrake/firedrake/local/lib/python2.7/site-packages/tsfc/fem.py", line 124, in __getitem__
    return self.tables[key]
KeyError: (VectorElement(FiniteElement('Real', interval, 0), dim=2), 0, (0,))

Maybe firedrake doesn't support R or a VectorElement thereof.