I need to reorder the use statements for the GUI to run, otherwise it crashes with
Traceback (most recent call last):
  File "defcon/defcon-gui.py", line 6, in <module>
    from PyQt4 import QtGui, QtCore
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class